/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.ImageIcon;
import juegos.BlackJack;

/**
 *
 * @author ALEX
 */
public class frmBlackJack extends javax.swing.JDialog {

    /**
     * Creates new form frmBlackJack
     */
    public frmBlackJack(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        iniciar();
    }
    BlackJack bj = new BlackJack();

   
   
    public void iniciar() {
        ImageIcon icono = new ImageIcon("F:\\2017\\Naipes\\BLACK JACK\\LOGOS\\curiosidades.png");
        ImageIcon icon = new ImageIcon("F:\\2017\\Naipes\\BLACK JACK\\LOGOS\\online-blackjack.png");
        ImageIcon icone = new ImageIcon("F:\\2017\\Naipes\\BLACK JACK\\LOGOS\\bJ.png");
        ImageIcon icon1 = new ImageIcon("F:\\2017\\Naipes\\BLACK JACK\\LOGOS\\PLAYER1.png");
        ImageIcon icon2 = new ImageIcon("F:\\2017\\Naipes\\BLACK JACK\\LOGOS\\PLAYER2.png");
        btnnaipe1.setIcon(bj.obtenerIconoReverse());
        btnnaipe2.setIcon(bj.obtenerIconoReverse());
        lbltitle.setIcon(icono);
        lblizq.setIcon(icon);
        lblder.setIcon(icone);
        lbljugadorA.setIcon(icon1);
        lbljugadorB.setIcon(icon2);
    }
    public void bloquearA(){
        btnnaipe1.setEnabled(false);
        btnplantarA.setEnabled(false);
        btnwin.setEnabled(false);
    }
    public void bloquearB(){
        btnnaipe2.setEnabled(false);
        btnplantarB.setEnabled(false);
        btnwin.setEnabled(false);
    }
    public void plantarA(){
        btnwin.setEnabled(true);
        btnnaipe1.setEnabled(false);
        btnnaipe2.setEnabled(true);
        btnplantarB.setEnabled(true);
    }
    public void plantarB(){
        btnwin.setEnabled(true);
        btnnaipe1.setEnabled(true);
        btnplantarA.setEnabled(true);
        btnnaipe2.setEnabled(false);
    }
    public void bloquearTodo(){
        btnnaipe1.setEnabled(false);
        btnplantarA.setEnabled(false);
        btnwin.setEnabled(false);
        btnnaipe2.setEnabled(false);
        btnplantarB.setEnabled(false);
    }
    public void limpiar() {
        btnnaipe1.setIcon(bj.obtenerIconoReverse());
        btnnaipe2.setIcon(bj.obtenerIconoReverse());
        lblganador.setText("");
        lblsumaA.setText("");
        lblsumaB.setText("");
        lblsumaA.setEnabled(true);
        lblsumaB.setEnabled(true);
        btnnaipe1.setEnabled(true);
        btnnaipe2.setEnabled(true);
        btnplantarA.setEnabled(true);
        btnplantarB.setEnabled(true);
        bj.reiniciar();
        btnwin.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnplantarA = new javax.swing.JButton();
        lblsumaA = new javax.swing.JLabel();
        lbljugadorA = new javax.swing.JLabel();
        btnnaipe1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnplantarB = new javax.swing.JButton();
        lblsumaB = new javax.swing.JLabel();
        lbljugadorB = new javax.swing.JLabel();
        btnnaipe2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnAgain = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnwin = new javax.swing.JButton();
        lblganador = new javax.swing.JLabel();
        lbltitle = new javax.swing.JLabel();
        lblizq = new javax.swing.JLabel();
        lblder = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnplantarA.setText("Plantar");
        btnplantarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplantarAActionPerformed(evt);
            }
        });

        lblsumaA.setBackground(new java.awt.Color(0, 0, 0));
        lblsumaA.setFont(new java.awt.Font("Impact", 1, 48)); // NOI18N
        lblsumaA.setForeground(new java.awt.Color(0, 153, 0));
        lblsumaA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblsumaA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnnaipe1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnnaipe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnaipe1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnnaipe1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbljugadorA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblsumaA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(btnplantarA)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbljugadorA, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblsumaA, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnnaipe1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnplantarA)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btnplantarB.setText("Plantar");
        btnplantarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplantarBActionPerformed(evt);
            }
        });

        lblsumaB.setBackground(new java.awt.Color(0, 0, 0));
        lblsumaB.setFont(new java.awt.Font("Impact", 1, 48)); // NOI18N
        lblsumaB.setForeground(new java.awt.Color(0, 153, 0));
        lblsumaB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblsumaB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnnaipe2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnnaipe2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnaipe2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addComponent(btnplantarB)
                .addGap(148, 148, 148))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblsumaB, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbljugadorB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnnaipe2, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(lbljugadorB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblsumaB, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnnaipe2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnplantarB)
                .addGap(16, 16, 16))
        );

        btnAgain.setText("PLAY AGAIN");
        btnAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgainActionPerformed(evt);
            }
        });

        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnwin.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnwin.setText("WIN");
        btnwin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnwinActionPerformed(evt);
            }
        });

        lblganador.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblganador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblganador.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Ganador", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblganador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnwin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(btnwin, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblganador, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgain, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblizq, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblder, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblizq, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblder, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnplantarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplantarAActionPerformed
        // TODO add your handling code here:
        plantarA();
    }//GEN-LAST:event_btnplantarAActionPerformed

    private void btnwinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnwinActionPerformed
        // TODO add your handling code here:
        bloquearA();
        bloquearB();
        if (bj.mostrarsumaA() != bj.mostrarsumaB()) {
            if (bj.mostrarsumaA() > bj.mostrarsumaB()) {
                lblganador.setText("A");
            } else {
                lblganador.setText("B");
            }
        }else{
            lblganador.setText("=");
        }

    }//GEN-LAST:event_btnwinActionPerformed

    private void btnplantarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplantarBActionPerformed
        // TODO add your handling code here:
        plantarB();
        
    }//GEN-LAST:event_btnplantarBActionPerformed

    private void btnAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgainActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnAgainActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnnaipe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnaipe1ActionPerformed
        // TODO add your handling code here:
        bloquearB();
        btnnaipe1.setIcon(bj.obtenerCartaA());
        lblsumaA.setText(String.valueOf(bj.mostrarsumaA()));
        if (bj.mostrarsumaA() == 21) {
            lblganador.setText("A");
            bloquearTodo();
        }
        if (bj.mostrarsumaA() > 21) {
            bloquearA();
            lblganador.setText("B");           
        }
    }//GEN-LAST:event_btnnaipe1ActionPerformed

    private void btnnaipe2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnaipe2ActionPerformed
        // TODO add your handling code here:
        bloquearA();
        btnnaipe2.setIcon(bj.obtenerCartaB());
        lblsumaB.setText(String.valueOf(bj.mostrarsumaB()));
        if (bj.mostrarsumaB() == 21) {
            lblganador.setText("B");
           bloquearTodo();
        }
        if (bj.mostrarsumaB() > 21) {
           bloquearB();
            lblganador.setText("A");          
        }
    }//GEN-LAST:event_btnnaipe2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBlackJack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBlackJack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBlackJack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBlackJack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmBlackJack dialog = new frmBlackJack(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgain;
    private javax.swing.JButton btnnaipe1;
    private javax.swing.JButton btnnaipe2;
    private javax.swing.JButton btnplantarA;
    private javax.swing.JButton btnplantarB;
    private javax.swing.JButton btnwin;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblder;
    private javax.swing.JLabel lblganador;
    private javax.swing.JLabel lblizq;
    private javax.swing.JLabel lbljugadorA;
    private javax.swing.JLabel lbljugadorB;
    private javax.swing.JLabel lblsumaA;
    private javax.swing.JLabel lblsumaB;
    private javax.swing.JLabel lbltitle;
    // End of variables declaration//GEN-END:variables
}
